dataset:
  name: amazon
  # root_path: /home/heyjoonkim/Universal-Domain-Adaptation/data/ # /path/to/dataset/root
  root_path: /home/heyjoonkim/data/datasets/ # /path/to/dataset/root
  num_common_class: 2
  num_source_class: 2
  source_domain: books
  target_domain: kitchen
  
model:
  model_name_or_path: bert-base-uncased

train:
  # train: False              # train model <-> only test model
  train: True                 # train model <-> only test model
  max_length: 512             # max length for tokenizer
  batch_size: 4         
  num_train_epochs: 10        # total training epoch 
  lr: 0.01 
  lr_scheduler_type: linear   # scheduler type
  early_stop: 3               # early stopping epoch
  seed: 1234                  # random seed
  multi: 0.1                  # loss weight

test:
  batch_size: 64

log:
  output_dir: /home/heyjoonkim/data/universal_domain_adaptation/