data:
  dataset:
    name: office # choices are ['office', 'officehome', 'caltech-imagenet', 'visda2017']
    root_path: /home/heyjoonkim/Universal-Domain-Adaptation/data/office # /path/to/dataset/root
    # office : amazon (0), dslr (1), webcam (2)
    source: 0 # source domain index
    target: 1 # target domain index
    n_share: 10 # number of classes to be shared
    n_source_private: 10 # number of classes in source private domain
    n_total: 31 # number of classes in total

  dataloader:
    class_balance: true #
    data_workers: 3 # how many workers to use for train dataloaders
    batch_size: 32 # batch_size for source domain and target domain respectively

model:
  base_model: resnet50 # choices=['resnet50', 'vgg16']
  # pretrained_model: /workspace/fubo/resnet50.pth # /path/to/pretrained/model

train:
  min_step: 20000 # minimum steps to run. run epochs until it exceeds the minStep
  lr: 0.001 # learning rate for new layers. learning rate for finetune is 1/10 of lr
  weight_decay: 0.0005
  momentum: 0.9
  early_stop: 100   # early stopping epoch
  # from original code
  # https://github.com/Solacex/Domain-Consensus-Clustering/blob/main/config/office.yaml
  interval: 2
  max_search: 3
  drop: 4

test:
  test_only: False # test a given model and exit
  threshold: 0.5 # hyper-parameter w

misc:
  gpus: 1 # how many GPUs to be used, 0 indicates CPU only

log:
  root_dir: log # the log directory (log directory will be {root_dir}/{method}/time/)